### ISSUE TITLE
Multilingual website

### ISSUE THREAD

**Issue by CimplexAB** [blendinteractive/Blend.Sitemap.Umbraco#3]
I have a multilingual website but I get zero pages in the sitemap, do you know if it is suppose to work or can it be a bug? 
![image](https://github.com/blendinteractive/Blend.Sitemap.Umbraco/assets/21332350/fe1afbde-a59d-4283-a863-44b4c9648888)

**Comment by chase-burandt** [comment]
This package hasn't been tested with multilingual as we don't have many requests for a multilingual site.
I'll take a look and troubleshoot.

Curious are you using using the Umbraco 10 or 11 version?

**Comment by CimplexAB** [comment]
Hi Chase! Thanks for the reply! The website I tried on was on latest Umbraco 11. Let me know if I can assist somehow! H5YR!

**Comment by chase-burandt** [comment]
I have pushed an update and here is MR for it: https://github.com/blendinteractive/Blend.Sitemap.Umbraco/pull/4/files

I did have to make a significant change to the LoadPages method in the SitemapBuilder.  This update loops through all languages configured on the site. Finds the default language and uses that URL for the <loc> then adds <xhml:link> for all additional languages.

Please take a look at the updates and let me know if you have any other suggestions or concerns.

**Comment by chase-burandt** [comment]
I have merged this update. Give it try.

**Comment by CimplexAB** [comment]
Hi Chase, great job! I just tried the update and it looks like everything works except when I try to use the setting 
`"ExcludeBoolFieldAlias": "noIndex"`

My setup is that I have a PageComposition with a bool property "noIndex" then I inherit the composition on all my pages.

The error I get is:
`System.ArgumentNullException: Value cannot be null. (Parameter 'key1')
   at Umbraco.Cms.Core.Collections.CompositeStringStringKey..ctor(String key1, String key2)
   at Umbraco.Cms.Infrastructure.PublishedCache.Property.GetSourceValue(String culture, String segment)
   at Umbraco.Cms.Infrastructure.PublishedCache.Property.HasValue(String culture, String segment)
   at Umbraco.Extensions.PublishedContentExtensions.Value[T](IPublishedContent content, IPublishedValueFallback publishedValueFallback, String alias, String culture, String segment, Fallback fallback, T defaultValue)
   at Umbraco.Extensions.FriendlyPublishedContentExtensions.Value[T](IPublishedContent content, String alias, String culture, String segment, Fallback fallback, T defaultValue)
   at Blend.Sitemap.SitemapBuilder.<LoadPages>b__15_0(IPublishedContent x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Blend.Sitemap.SitemapBuilder.LoadPages()
   at Blend.Sitemap.SitemapBuilder.<GetSitemap>b__14_0()
   at Umbraco.Extensions.AppCacheExtensions.<>c__DisplayClass0_0`1.<GetCacheItem>b__0()
   at Umbraco.Cms.Core.Cache.SafeLazy.<>c__DisplayClass1_0.<GetSafeLazy>b__0()`

**Comment by chase-burandt** [comment]
Hi Herman,

It took me a bit to recreate the issue. This happens when the toggle data types is set to vary by culture.

When it is not vary by culture, The setting that is used is from the default language.

I will take a look and get a patch out there for allowing to this setting to vary by culture.

**Comment by chase-burandt** [comment]
I have updated the package so the exclude toggle can vary by culture.

Example the default language doesn't have the property set to true. Then another language has this property set to true.
The result will be the default language displays and is in the sitemap, but the langue alternate does not display.

If the default langue is set to not display page, then the page is completely removed from the sitemap.

**Comment by CimplexAB** [comment]
Great job! I upgraded and it works. H5YR!
